# Generated by Django 4.2.4 on 2023-09-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profil.jpg', upload_to='profile_photo/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('programming', 'Programming'), ('fitness', 'Fitness'), ('health', 'Health'), ('finance', 'finance'), ('money', 'money'), ('education', 'education'), ('food', 'food')], max_length=20),
        ),
    ]
