# Generated by Django 4.2.4 on 2023-09-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_profile_photo_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photo/profil.jpg', upload_to='profile_photo/'),
        ),
    ]
